format_version: v1.0
type: UniqueComponent
attributes: {id: drvWifiWinc}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_WIFI_WINC1500_VERSION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 19.7.7}
  - type: Combo
    attributes: {id: DRV_WIFI_WINC_DRIVER_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Socket Mode}
  - type: Menu
    attributes: {id: DRV_WIFI_WINC_DRV_SPI_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_11}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_12}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_13}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_14}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_8}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_SELECT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: '7'}
  - type: Combo
    attributes: {id: DRV_WIFI_WINC_LOG_LEVEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: DRV_WIFI_WINC_RTOS_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: DRV_WIFI_WINC_SPI_INST}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: drv_spi_0}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_SPI_INST_IDX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: '0'}
  - type: File
    attributes: {id: DRV_WIFI_WINC_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_USE_SYS_DEBUG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_USE_TCPIP_STACK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: File
    attributes: {id: WDRV_WINC_ENTERPRISE_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WDRV_WINC_ENTERPRISE_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_ECC_TYPES_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_FLEXIBLE_FLASH_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_FLEXIBLE_FLASH_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_INET_ADDR_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_INET_NTOP_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_HIF_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_HIF_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_OTA_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_OTA_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_PERIPH_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_PERIPH_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_SOCKET_HOST_IF_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_SSL_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_SSL_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_TYPES_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_WIFI_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_M2M_WIFI_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NETINET_IN_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NMASIC_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NMASIC_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NMBUS_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NMBUS_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NMDRV_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NMDRV_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NMSPI_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NMSPI_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NM_BSP_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NM_COMMON_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NM_COMMON_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_NM_DEBUG_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_SOCKET_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_SOCKET_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_SPI_FLASH_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_SPI_FLASH_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_7_SPI_FLASH_MAP_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_spi_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_spi_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_spi}
  - type: DirectDependency
    attributes: {id: spi_dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '30', y: '200', id: drvWifiWinc}
