configName: sam_e54_xpro_winc1500_freertos
folderName: sam_e54_xpro_winc1500_freertos
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME54P20A
projectName: sam_e54_xpro_winc1500_freertos
settings:
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.6.95\atdf\ATSAME54P20A.atdf
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  MERGE_STRATEGY: USER_ALL
  PackageFilter: bsp;core;core_apps_pic32mz_w1;crypto;csp;dev_packs;net;quick_docs;usb;wireless_apps_pic32mzw1_wfi32e01;wireless_apps_winc1500;wireless_apps_winc3400;wireless_system_pic32mzw1_wfi32e01;wireless_wifi
